'use strict'

const constants = {
  ID: 'ID',
  id: 'id',
  string: 'String',
  int: 'Int',
  float: 'Float',
  boolean: 'Boolean',
  email: 'email',
  emails: 'emails',
  phone: 'phone',
  phones: 'phones',
  name: 'name',
  names: 'names',
  first: 'first',
  firstName: 'firstname',
  lastName: 'lastname',
  last: 'last',
  fullName: 'fullname',
  fullNames: 'fullnames',
  age: 'age',
  ages: 'ages',
  gender: 'gender',
  genders: 'genders',
  prefix: 'prefix',
  prefixes: 'prefixes',
  profession: 'profession',
  professions: 'professions',
  date: 'date',
  dates: 'dates',
  address: 'address',
  addresses: 'addresses',
  city: 'city',
  cities: 'cities',
  country: 'country',
  countries: 'countries'
}

module.exports = constants
